apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  POSTGRES_DB: {{ .Values.database.instance }}
  POSTGRES_USER: {{ .Values.database.username }}
  POSTGRES_PASSWORD: {{ .Values.database.password }}
