apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  type: LoadBalancer
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.deployment.container_port }}
      targetPort: {{ .Values.deployment.container_port }}
      name: postgres
  selector:
    app: {{ .Values.deployment.name }}
